name: Changelog updated

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  check-changelog:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Fetch main branch
      run: git fetch origin main

    - name: Check if changelog is updated
      run: |
        if git diff --name-only origin/main ${{ github.sha }} | grep -q 'docs/additional_information/changelog.rst'; then
          echo "Changelog has been updated."
        else
          echo "::error::Changelog has not been updated."
          exit 1
        fi