name: Test Notebooks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-notebooks:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # Only for one python version to save on resources

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install nbconvert jupyter

      # Install dtaianomaly locally
      - name: Install dtaianomaly
        run: pip install .

      # Test the notebooks
      - name: Execute Notebooks
        run: |
          for notebook in $(find ./notebooks -name "*.ipynb"); do
            jupyter nbconvert --to notebook --execute $notebook
          done
